##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. See LICENSE file
## in root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_screen
description: A package for managing screens.
version: 0.2.0
repository: https://github.com/robmllze/df_screen

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 < 4.0.0"
  flutter: ">=3.0.0 < 4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter
  df_generate_dart_models_core: ^0.2.0
  df_debouncer: ^0.1.2
  df_pod: ^0.2.3
  df_log: ^0.1.2
  df_scalable: ^0.1.2
  device_info_plus: ^10.1.1
  after_layout: ^1.2.0

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
